version: '3.8'
services:
  # redis:
    # image: redis:alpine
  web:
    build: .
    image: ticket-system-backend
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    # depends_on:
      # - redis
