# Generated by Django 3.1.7 on 2021-10-12 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userAuth.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0002_remove_ticket_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_users',
            field=models.ManyToManyField(related_name='assigned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(default=userAuth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closer', 'Closed')], default='Open', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_date',
            field=models.IntegerField(default=20211012),
        ),
    ]
