# Generated by Django 3.1.7 on 2021-10-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20211012_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Closed')], default=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_date',
            field=models.IntegerField(default=20211013),
        ),
    ]
