# Generated by Django 3.1.7 on 2021-10-18 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_auto_20211013_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_date',
            field=models.IntegerField(default=20211018),
        ),
    ]
