# Generated by Django 3.1.7 on 2021-10-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20211018_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_date',
        ),
    ]
