# Generated by Django 3.1.7 on 2021-10-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_auto_20211018_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[(3, 'Normal'), (1, 'Critical'), (2, 'High'), (4, 'Low'), (5, 'Very Low')], default=3, null=True),
        ),
    ]
