# Generated by Django 3.1.7 on 2021-10-18 15:10

from django.conf import settings
from django.db import migrations, models
import userAuth.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0012_auto_20211018_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, default=[userAuth.models.User], related_name='assigned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 'Critical'), (2, 'High'), (3, 'Normal'), (4, 'Low'), (5, 'Very Low')], default=3),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Open'), (2, 'Closed')], default=1),
        ),
    ]
