# Generated by Django 3.1.7 on 2021-02-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
